#
#  THIS MUST BE PLACED AT /usr/share/pipewire/pipewire.conf.d
#  For some reason it seems to not work when placed in a user's dot files (wtf)
#


context.modules = [
    {   name = libpipewire-module-loopback
        args = {
            node.description = "Qu-SB Monitors"
            capture.props = {
                node.name = "Qu-SB Monitors"
                media.class = "Audio/Sink"
                audio.position = [ FL FR ]
            }
            playback.props = {
                node.name = "Qu-SB Output Stream"
                audio.position = [ AUX30 AUX31 ]
                # target.object = "alsa_output.usb-Allen_Heath_Ltd_QU-SB-01.pro-output-0"
                stream.dont-remix = true
                node.passive = true
            }
        }
    }
]
